
# Site settings

url: "https://ridersofrohan306.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

#baseurl: /personal-jekyll-theme

#google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally

force-https: True

#############
# HTML Head #
#############

author: "Rohan Chandra"
lang: "en"
title: "Rohan Chandra"
favicon: "/img/gohan.ico"
description: "Blog and website of John Smith, blogging mainly for tech. Opinions expressed are mine."
keywords: "smith, jones, personal, jekyll, theme"

aboutme: "Welcome to my website. My name is Rohan Chandra.I am a senior at Delhi Technological University, New Delhi. My hobbies are playing chess and mathemagics. The latter is a just a fancy term for vedic math or speed math. My favorite game is the one where you take apart the number from the number plate of the car in front of you and multiply it in your head. My record is 13 cars in 56 seconds. So the take away is you probably shouldn't get into a car with me. Thanks for visiting my site." #\SARTHAK

################
# Intro layout #
################

black-favicon: "/img/gohan.ico"
background-img: "../img/super_saiyan_god_goku_wallpaper_by_rayzorblade189-d7eaf19.jpg"
me-img: "/img/11412177_703829636427811_1554266896674547224_n.jpg"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "I'll either find a way or make one myself."
  - text: "Working towards the moment I transform into a supersaiyan."

########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
google-plus-share: True
linkedin-share: True
disqus-shortname: "panossakkos"

###############
# Life Events #
###############

events:
  - image: "/img/career/IIITD.png"
    date: "December 2015 - June 2016"
    description: "Future appointment as Research Assistant!"
  - image: "/img/career/amity-logo.png"
    date: "August 2015 - September 2015 "
    description: "Research Assistant working on classification and machine learning"
  - image: "/img/career/UMD.png"
    date: "June 2015 - August 2015"
    description: "Summer research intern under Drs. Piya Pal and Ashok Agrawala"
  - image: "/img/career/MECHARTES.jpg"
    date: "December 2014 - January 2015"
    description: "Worked as project design intern on a home automation project to design a biometric module based finger print sensing lock"
  - image: "/img/career/UCB.jpg"
    date: "June 2014 - August 2014"
    description: "Studied Urban and Finance Economics at the Berkeley summer"
  - image: "/img/career/DTU.jpg"
    date: "January 2014 - Present"
    description: "Research assistant in Dr. Neeta Pandey's group. Working to improve performance and functionality of analog filters and Digital to Analog Converters"


# USE THIS AS AN EXAMPLE \SARTHAK
###############
# Publications #
###############

collections:
  publications:
    output: true
    permalink: /publications/:path/
  # ADD OTHER STUFF HERE \SARTHAK  
relative_permalinks: false

# First image of the Career timeline
career-img: "/img/career/ashstart.jpg"

##################
# Contact layout #
##################

email: "rohanchandra30[at]gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/thegracefulwarrior"
  #- title: "twitter"
   # url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/ridersofrohan306"
 # - title: "bitcoin"
  #  url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
 # - title: "rss"
    #url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Research: 'research'
  Career+Resumé: 'career'
  Publications: 'publication'
  Speed Math Blog: 'blog'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]

gems: [jekyll-paginate]
